init;
show sites;
define site s1 127.0.0.1:8000, s2 127.0.0.1:9000;
show sites;
show tables;
create table book (id int key, title char(20), author char(20));
show tables;
show fragments;
fragment book horizontally into id>100, id<=100;
show fragments;
allocate book.1 to s1;
allocate book.2 to s2;
insert into book values (1, 'hello', 'Jack');
insert into book values (101, 'world', 'Mike');
create table student (id int key, stu_name char(20), age int);
fragment student vertically into (id, stu_name), (id, age);
allocate student.1 to s1;
allocate student.2 to s2;
insert into student values (1, 'jiang', 21);
delete from book where author='Mike';
delete from student where age=21;
quit;